version: "3"
services:
  database:
    image: postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "/minitwit_db:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  go-web-app:
    restart: unless-stopped
    container_name: app
    network_mode: host
    ports:
      - "5000:5000"
    build:
      dockerfile: Dockerfile
      context: ./app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - database
  nginx:
     image: nginx:1.17
     container_name: reverse-proxy
     restart: unless-stopped
     network_mode: host
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./nginx:/etc/nginx/
