version: "3"
services:
  go-web-app:
    restart: unless-stopped
    network_mode: host
    container_name: app
    ports:
      - "80:5000"
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - "/tmp:/tmp"
  #nginx:
  #  image: nginx:1.17
  #  container_name: reverse-proxy
  # restart: unless-stopped
  #  network_mode: host
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./nginx:/etc/nginx/
