version: "3"
services:
  go-web-app:
    image: gruppe11/devops-prod:latest
    restart: unless-stopped
    container_name: app
    network_mode: host
    ports:
      - "5000:5000"
    volumes:
      - "/tmp:/tmp"
  nginx:
    image: nginx:1.17
    container_name: reverse-proxy
    restart: unless-stopped
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/
