version: "3"
services:
  go-web-app:
    restart: unless-stopped
    network_mode: host
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - "/tmp:/tmp"
  nginx:
    image: nginx:1.17
    container_name: reverse-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx:/etc/nginx/
