version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
       - "5000:5000"
    environment:
      - VIRTUAL_HOST=127.0.0.1
      - LETSENCRYPT_HOST=127.0.0.1
