name: Deploy-dev
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@master
    - name: Linter
      uses: shoukoo/golang-pipeline/go1.13/linter@master
      env:
        PROJECT_PATH: "./app/"
    - name: Test
      uses: shoukoo/golang-pipeline/go1.13/test@master
      env:
        PROJECT_PATH: "./app/"
    - name: Imports
      uses: grandcolline/golang-github-actions@v1.1.0
      env:
        PROJECT_PATH: "./app/"
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: ErrCheck
      uses: grandcolline/golang-github-actions@v1.1.0
      env:
        PROJECT_PATH: "./app/"
      with:
        run: errcheck
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Shadow
      uses: grandcolline/golang-github-actions@v1.1.0
      env:
        PROJECT_PATH: "./app/"
      with:
        run: shadow
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: StaticCheck
      uses: grandcolline/golang-github-actions@v1.1.0
      env:
        PROJECT_PATH: "./app/"
      with:
        run: staticcheck
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: SecurityCheck
      uses: grandcolline/golang-github-actions@v1.1.0
      env:
        PROJECT_PATH: "./app/"
      with:
        run: sec
        token: ${{ secrets.GITHUB_TOKEN }}
        flags: "-exclude=G104"
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@master
    - name: publish docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gruppe11/devops-test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: "./app"
        tags: "latest"
    - name: Deploy on DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_IP_TEST }}
        USERNAME: ${{ secrets.ROOT }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: |
         cd ../var/www/devops/
         rm ../../../tmp/minitwit.db
         docker login
         ${{ secrets.DOCKER_USERNAME }}
         ${{ secrets.DOCKER_PASSWORD }}
         docker-compose -f docker-compose.dev.yaml pull
         docker-compose -f docker-compose.dev.yaml up -d
  integration-test:
    runs-on: ubuntu-latest
    name: IntegrationTest
    steps:
    - uses: actions/checkout@master
    - name: Scenario test
      run: |
        cd simulator
        python3 minitwit_simulator.py "http://142.93.238.65/simulator" | grep . && exit 1 || exit 0

