name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: publish docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gruppe11/devops
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: "./app"  
    - name: deploy docker to Digital Ocean
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
       echo "ssh begin"
       ssh -o StrictHostKeyChecking=no ${{secrets.ROOT}}@${{DO_IP}}
       echo "change directory to devops"
       cd ../var/www/devops
       echo "Run docker pull_request"
       docker-compose pull_request
       echo "Run docker compose"
       docker-compose -f docker-compose.prod.yaml up -d
