on:
  push:
    branches-ignore: 
      - 'develop'
      - 'master' 
name: build
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.13  linters
      uses: shoukoo/golang-pipeline/go1.13/linter@master
    - name: go1.13 test
      uses: shoukoo/golang-pipeline/go1.13/test@master
      env:
        PROJECT_PATH: "./app/"
